server:
  port: 8082 # Cổng của order-service

spring:
  application:
    name: order-service
  
  # KẾT NỐI SUPABASE
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.fjcsbzomnyncdjefnwoa
    password: PhanTanMinh123%
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # KẾT NỐI KAFKA
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-group

# KẾT NỐI EUREKA
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true