version: '3.8'
services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - jenkins-net
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root # Để chạy được docker trong docker dễ dàng hơn
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # Thay đổi ở đây: Trỏ trực tiếp vào thư mục cũ của bạn
      - /home/quyen/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - jenkins-net
    depends_on:
      - sonarqube

networks:
  jenkins-net:
